services:
   postgres:
      container_name: postgres
      image: local/sample-clojure
      environment:
      ###this ones can be set as a secret file on a production deploy, nothing to worry about
      ### since this is a sample project
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PW}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "5432:5432"
      restart: always
  